### ISSUE TITLE
Support locking the version of standard

### ISSUE THREAD

**Issue by danielwestendorf** [andrewmcodes/standardrb-action#12]
# Bug Report 

## Describe the bug

Using this supremely excellent github action on a real project, we found that standard was [updated today](https://rubygems.org/gems/standard/versions/0.8). Since this project installs the latest version of standard, new rules started to be enforced. This caused our deploys to break as new rules were enforced.

We'd like to upgrade standard versions on our own terms.

# To Reproduce

Have compliant code that is no longer compliant code. Cry a little.

# Expected behavior

The ability to lock a version of standard so that upgrades are explicit. If no version is specified, install the latest.

```bash
# lib/entrypoint.sh
#!/bin/sh

set -e

if [[ -z "${STANDARDRB_VERSION}" ]]; then
  gem install standard -v $STANDARDRB_VERSION
else
  gem install standard
fi

ruby /action/lib/index.rb
```

I'm unsure if ENV vars specified in the GH action are automatically shared with the docker container? If so, this may be the only change needed?

**Comment by drewbaumann** [comment]
I'm a bit confused why the gem is installed here. Doesn't bundler handle this? Would love to learn more!

**Comment by andrewmcodes** [comment]
@drewbaumann The gem is installed here so that this action can be used regardless of how you have standard set up locally. By installing it here, you can bypass any issues that could result in you bundle failing like missing c-extensions.

**Comment by andrewmcodes** [comment]
@danielwestendorf sorry for not seeing this earlier - I forgot this even existed 😬

You are correct about how a version constraint could be implemented. We did this very early on with the Rubocop version of this action that you can see [on this pull request to the project here](https://github.com/bbugh/rubocop-linter-action/blob/4173a14eb7bb2970678b832656bd0a261e345535/lib/entrypoint.sh#L12). 

To be totally honest I have absolutely no desire to make changes to this project and I'm really surprised it works. 

The RuboCop version became a nightmare and I recently decided to stop supporting it. The reasoning was laid out [here](https://github.com/andrewmcodes/rubocop-linter-action/blob/master/README.md#introduction). 

So all this being said I'd love to convince you that you shouldn't use this project BUT if you truly find it valuable I'm willing to make this update for you. 

As a note for those who may read this in the future: this is not an invitation for feature requests 😬

**Comment by danielwestendorf** [comment]
Thanks for the response, @andrewmcodes. 

I don't think this actually needs to be implemented. I understand your reasoning and agree with it. I have my own mess of linter github actions :).

The best part of standard is that it isn't configurable, which simplifies things quite a bit. We'll continue to use this action, without guarantee, as-is.
