### ISSUE TITLE
Unpublish from GitHub marketplace?

### ISSUE THREAD

**Issue by searls** [andrewmcodes/standardrb-action#27]
Hi Andrew, it was suggested in our fork of this repo that this one should be unpublished from the marketplace in favor of the one on the @standardrb org: https://github.com/standardrb/standard-ruby-action/issues/8

I saw your deprecation/warning at the top of the README and I'm inclined to agree that the action as it exists isn't in a recommendable state right now, but we're hoping to improve it and publish that

**Comment by andrewmcodes** [comment]
@searls I will see what I can do!

**Comment by andrewmcodes** [comment]
@searls Ok it should be gone. If you want to update the readme to point to your fork, I will accept that PR 👍

**Comment by searls** [comment]
Thanks! https://github.com/andrewmcodes/standardrb-action/pull/28
